services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: web123
      POSTGRES_DB: books
    ports:
      - 9999:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
